
language: objective-c
osx_image: xcode9

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8

notifications:
  email: false

before_install:

    - env
    - locale
    - xcpretty --version
    - xcodebuild -version
    - xcodebuild -showsdks

script:
    - set -o pipefail
    - xcodebuild clean build -project Unicorn.xcodeproj -target 'Unicorn iOS' -sdk iphonesimulator -configuration Debug | xcpretty
    - xcodebuild clean build -project Unicorn.xcodeproj -target 'Unicorn watchOS' -sdk watchsimulator -configuration Debug | xcpretty
    - xcodebuild clean build -project Unicorn.xcodeproj -target 'Unicorn tvOS'  -sdk appletvsimulator -configuration Debug | xcpretty
    - xcodebuild clean build -project Unicorn.xcodeproj -target 'Unicorn macOS' -sdk macosx -configuration Debug | xcpretty
